language: node_js
node_js:
  - 8
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - node_modules
install:
  yarn
script:
  - yarn lint
  - yarn test:unit
  - yarn test:e2e